[package]
name = "kernel"
version = "0.1.0"
edition = "2021"


[dependencies]


# compiler settings

[profile.dev]
panic = "abort" #by default it is usually "unwind"

[profile.release]
panic = "abort" #by default it is usually "unwind"

[unstable]
build-std = ["core", "compiler-builtins"]

